<a href="https://colab.research.google.com/github/RazvanGolan/Faculty-3rd-year/blob/main/pi/lab2/exercises_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# exercise 1

a = torch.rand((5))
b = torch.rand((3,4))
c = torch.rand((2,3,5))

print(f'a = {a}, shape = {a.shape}')
print(f'b = {b}, shape = {b.shape}')
print(f'c = {c}, shape = {c.shape}')

a = tensor([0.5492, 0.6109, 0.2549, 0.6160, 0.6518]), shape = torch.Size([5])
b = tensor([[0.4940, 0.0561, 0.5804, 0.8131],
        [0.8691, 0.0182, 0.0850, 0.6912],
        [0.0352, 0.7284, 0.3806, 0.6026]]), shape = torch.Size([3, 4])
c = tensor([[[0.7401, 0.1347, 0.0412, 0.3536, 0.2935],
         [0.2526, 0.4492, 0.5287, 0.2117, 0.6128],
         [0.8164, 0.0490, 0.9502, 0.8438, 0.2009]],

        [[0.5082, 0.8759, 0.0683, 0.6550, 0.1159],
         [0.8152, 0.2592, 0.8371, 0.8145, 0.0269],
         [0.8095, 0.8041, 0.0450, 0.2508, 0.2530]]]), shape = torch.Size([2, 3, 5])


In [ ]:
# exercise 2

x = torch.tensor([-10, 10, 8], dtype = torch.float64, requires_grad=True)

y = 1/(1 + torch.exp(-x))
y = y.sum()
y.backward()

x.grad

tensor([4.5396e-05, 4.5396e-05, 3.3524e-04], dtype=torch.float64)

In [ ]:
# exercise 3

A = torch.tensor([[1, 2, -3], [4, 5, 10]])
B = torch.tensor([[10, 11, -2], [13, -3, 8]])

print("A: ")
print(A)

print("B: ")
print(B)

print("Hadamard product: ")
print(A * B)

print("B + 10:")
print(b + 10)

print("A transpose:")
print(A.T)

print("B transpose:")
print(B.T)

A: 
tensor([[ 1,  2, -3],
        [ 4,  5, 10]])
B: 
tensor([[10, 11, -2],
        [13, -3,  8]])
Hadamard product: 
tensor([[ 10,  22,   6],
        [ 52, -15,  80]])
B + 10:
tensor([[20, 21,  8],
        [23,  7, 18]])
A transpose:
tensor([[ 1,  4],
        [ 2,  5],
        [-3, 10]])
B transpose:
tensor([[10, 13],
        [11, -3],
        [-2,  8]])


In [51]:
# exercise 4

A = torch.arange(6).reshape(2,3)
A += 1
B = torch.tensor([[10, 11], [-2, 0], [1, -3]])

print("A: ")
print(A)

print("B: ")
print(B)

print("A @ B:")
print(A @ B)

print("Frobenius norm of A:")
print(torch.norm(A.type(torch.float64)))

print("Frobenius norm of B:")
print(torch.norm(B.type(torch.float64)))

A: 
tensor([[1, 2, 3],
        [4, 5, 6]])
B: 
tensor([[10, 11],
        [-2,  0],
        [ 1, -3]])
A @ B:
tensor([[ 9,  2],
        [36, 26]])
Frobenius norm of A:
tensor(9.5394, dtype=torch.float64)
Frobenius norm of B:
tensor(15.3297, dtype=torch.float64)
